### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by jorrete** [jrconlin/pywebpush#12]
I can't make it work. I've run the testsuite and fails:
```
======================================================================
ERROR: test_encode (test_webpush.WebpushTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorro/tmp/pywebpush/pywebpush/tests/test_webpush.py", line 67, in test_encode
    subscription_info = self._gen_subscription_info(recv_key)
  File "/home/jorro/tmp/pywebpush/pywebpush/tests/test_webpush.py", line 18, in _gen_subscription_info
    'auth': base64.urlsafe_b64encode(os.urandom(16)).strip('='),
TypeError: 'str' does not support the buffer interface

======================================================================
ERROR: test_init (test_webpush.WebpushTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorro/tmp/pywebpush/pywebpush/tests/test_webpush.py", line 54, in test_init
    "keys": {'p256dh': 'AAA=', 'auth': 'AAA='}})
  File "/usr/lib64/python3.4/unittest/case.py", line 742, in assertRaises
    return context.handle('assertRaises', callableObj, args, kwargs)
  File "/usr/lib64/python3.4/unittest/case.py", line 200, in handle
    callable_obj(*args, **kwargs)
  File "/home/jorro/tmp/pywebpush/pywebpush/__init__.py", line 99, in __init__
    self._repad(keys['p256dh'].encode('utf8')))
  File "/home/jorro/tmp/pywebpush/pywebpush/__init__.py", line 108, in _repad
    return str + "===="[:len(str) % 4]
TypeError: can't concat bytes to str

======================================================================
ERROR: test_send (test_webpush.WebpushTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorro/.virtualenvs/pywebpush/lib/python3.4/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/jorro/tmp/pywebpush/pywebpush/tests/test_webpush.py", line 96, in test_send
    subscription_info = self._gen_subscription_info(recv_key)
  File "/home/jorro/tmp/pywebpush/pywebpush/tests/test_webpush.py", line 18, in _gen_subscription_info
    'auth': base64.urlsafe_b64encode(os.urandom(16)).strip('='),
TypeError: 'str' does not support the buffer interface

Name           Stmts   Miss  Cover
----------------------------------
pywebpush.py      63     23    63%
----------------------------------------------------------------------
Ran 4 tests in 0.006s

FAILED (errors=3)
```
Is there a working version. BTW I've used python3 to run the suite.
Thanks.

**Comment by jrconlin** [comment]
Ah, the library was written for 2.7. I haven't tested against 3+. I can't
work on it today, but will try to get it compliant Monday.

**Comment by jrconlin** [comment]
See https://github.com/mozilla-services/pywebpush/pull/
