### ISSUE TITLE
TypeError: character mapping must return integer, None or unicode

### ISSUE THREAD

**Issue by groovecoder** [jrconlin/pywebpush#8]
I'm getting the `subscription_info` via `json.loads(subscription_json)`:
```
ipdb> p subscription_info
{u'keys': {u'p256dh': u'BDZunuhU7jWX_CoVY7PEUctjX0ZCvmXRN67qCwXTuk3tHhql8i71AmQ73G8HCJ2ZDVtAQJkwTY-hSYRCs7DsbKQ', u'auth': u'elTYtoRvpbTpWYR6iLhHww'}, u'endpoint': u'http://ec2-54-84-164-111.compute-1.amazonaws.com:8082/push/v1/gAAAAABXOyv_ayNsIbjLrhxE34Cw6_5ywJ2FX5i5g-n6Pkq5xUt4zs8k4WAEcnD-o6pxJAQNCEOaEPL5paNT03-eI44s8mopUiPHnj4JNco0tyNpoh_yBL58kbP1ZNtSQTdLEw1G-Bdi'}
```
But when I pass this `subscription_info` object into `WebPusher`, I get:
```
Traceback (most recent call last):
  File "/Users/lcrouch/code/push-dev-dashboard/dashboard/tests/test_e2e.py", line 124, in test_e2e
    WebPusher(subscription).send(message)
  File "/Users/lcrouch/python/push-dev-dashboard/lib/python2.7/site-packages/pywebpush/__init__.py", line 72, in __init__
    receiver_raw = base64.urlsafe_b64decode(self._repad(keys['p256dh']))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 116, in urlsafe_b64decode
    return b64decode(s.translate(_urlsafe_decode_translation))
TypeError: character mapping must return integer, None or unicode
```

**Comment by safwanrahman** [comment]
So the problem is, the ``keys`` are in unicode object. But it should be a sting rather than unicode. I have also faced the same problem and made [this](https://github.com/safwanrahman/django-webpush/blob/master/webpush/utils.py#L38) approach.
I hope it will be a workover of this. Otherwise, I can take a look to fix this from this package itself

**Comment by jrconlin** [comment]
Yeah, the problem is that it's not being restricted to utf8 encoding. I'll have a patch ready in a bit.
